biapy_cyrus:
    resource: "@BiapyCyrusBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

default:
  pattern: /
  defaults:
      _controller: SonataAdminBundle:Core:dashboard

admin_dashboard:
    pattern: /admin/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# redirect routes for the non-locale routes
admin_without_locale:
    pattern: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

admin_dashboard_without_locale:
    pattern: /admin/dashboard
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true # this for 301

login:
    pattern: /login
    defaults:  { _controller: BiapySecurityBundle:Security:login }
       
login_check:
    pattern:   /login_check
    
logout:
    pattern: /logout
    
    
    
    
    
    
    
