jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Biapy\CyrusBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN_DOMAIN: ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_USER
            - ROLE_ADMIN_DOMAIN
            - ROLE_ALLOWED_TO_SWITCH

    providers:
       #main:
       #     entity: { class: Biapy\CyrusBundle\Entity\User, property: username }
        administrators:
            entity: { class: BiapyCyrusBundle:User }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   /logout
                target: /
                invalidate_session: false

    access_control:
        - { path: ^/login.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/biapy/cyrus/domain/.*, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/biapy/cyrus/senderwatch/.*, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/biapy/.*, roles: ROLE_ADMIN_DOMAIN }
        - { path: ^/recovery.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/unauthorized.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user.*, roles: ROLE_USER }
        - { path: ^/.*, roles: ROLE_ADMIN_DOMAIN }

    access_denied_url: /unauthorized