Biapy\CyrusBundle\Entity\Domain:
  type: entity
  table: domain
  indexes:
    name_index:
      columns: [ name ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
      unique: true
      nullable: false
  oneToMany:
    users:
      targetEntity: User
      mappedBy: domain
    aliases:
      targetEntity: Alias
      mappedBy: domain
#  manyToMany:
#    adminUsers:
#      targetEntity: User
#      inversedBy: grantedDomains
#      joinTable:
#        name: domains_users
#        joinColumns:
#          domain_id:
#            referencedColumnName: id
#            onDelete: CASCADE
#            onUpdate: CASCADE
#        inverseJoinColumns:
#          user_id:
#            referencedColumnName: id
#            unique: false
#            onDelete: CASCADE
#            onUpdate: CASCADE
      
  manyToMany:
      adminUsers:
        targetEntity: User
        mappedBy: grantedDomains
