Biapy\CyrusBundle\Entity\User:
  type: entity
  table: user
  uniqueConstraints:
    username_unique:
      columns: [ domain_id, username ]
  indexes:
    enabled_index:
      columns: [ enabled ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 255
      nullable: false
    password:
      type: string
      length: 64
      nullable: false
    enabled:
      type: boolean
      nullable: false
      options:
          default: true
    has_mailbox:
      type: boolean
      nullable: false
      options:
          default: true
    is_super_admin:
      type: boolean
      nullable: true
      options:
          default: false
    recovery_token:
      type: string
      length: 64
      nullable: true
    recovery_expiry:
      type: datetime
      nullable: true
  manyToOne:
    domain:
      targetEntity: Domain
      inversedBy: users
      joinColumn:
        name: domain_id
        nullable: false;
        referencedColumnName: id
        onDelete: CASCADE
        onUpdate: CASCADE

  manyToMany:
    grantedDomains:
      targetEntity: Domain
      inversedBy: adminUsers
      joinTable:
        name: domains_users
        joinColumns:
          user_id:
            referencedColumnName: id
            onDelete: CASCADE
            onUpdate: CASCADE
        inverseJoinColumns:
          domain_id:
            referencedColumnName: id
            unique: false
            onDelete: CASCADE
            onUpdate: CASCADE

#  manyToMany:
#    grantedDomains:
#      targetEntity: Domain
#      mappedBy: adminUsers
