Biapy\CyrusBundle\Entity\User:
  type: entity
  table: user
  uniqueConstraints:
    username_unique:
      columns: [ domain_id, username ]
  indexes:
    enabled_index:
      columns: [ enabled ]
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 255
      nullable: false
    password:
      type: string
      length: 64
      nullable: false
    enabled:
      type: boolean
      nullable: false
    has_mailbox:
      type: boolean
      nullable: false
  manyToOne:
    domain:
      targetEntity: Domain
      inversedBy: users
      joinColumn:
        name: domain_id
        referencedColumnName: id
        onDelete: CASCADE
        onUpdate: CASCADE
